name: nel
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: "http://localhost:8080"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.0
  uuid: ^4.5.1
  azblob: ^4.0.0
#  random:
#    hosted: "http://localhost:8080"
#    version:

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
